name: Building PDF
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildPDF:
    name: Re:VIEW Workflow PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build PDF
        run: docker run -t --rm -v $(pwd):/book vvakame/review:3.2 /bin/bash -ci "cd /book && yarn && yarn build"
      - name: debug
        run: ls -lta && ls -lta ../ && ls -lta ./.review
      - uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: .review/寒川のカートコバーン.pdf
          if-no-files-found: error
          retention-days: 90
